language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - "sudo apt-get update -q"
  - "sudo apt-get install -y python3-lxml"
  - "pip install -r ./travis/requirements.txt"

script:
  - "python ./travis/test_json.py"
  - "py.test . -v --cov . --cov-report term-missing"

after_success:
  - "coveralls"

env:
  - PYTHONPATH=.
