language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
  - "pypy3"

cache: pip

install:
  - "sudo apt-get update -q"
  - "sudo apt-get install -y python3-lxml libenchant-dev"
  - "pip install -U pip setuptools"
  - "pip install -Ur requirements.txt"

script:
  - "py.test . -R : -v --cov . --cov-report term-missing --pylint --pylint-rcfile=travis/pylintrc --ignore=venv/ -p tests.pytest_json_lint"

env:
  - PYTHONPATH=.
  - PYTHONPATH=. PYTHONASYNCIODEBUG=1

matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "nightly"
